export let array = [
    { id: 'TX-EX-01',
      categoryTransaction: "jajan",
      colorTransaction: 'blue',
      dateTransaction: "2025-02-16",
      nameTransaction: "ASUS ROG RTX 58000",
      nominalTransaction: 28000000,
      noteTransaction: "Bjir sultan ",
      typeTransaction: "transactionExpense",
    },
    { id: 'TX-EX-02',
      categoryTransaction: "kebutuhan",
      colorTransaction: 'yellow',
      dateTransaction: "2015-11-16",
      nameTransaction: "Kulkas 5 pintu",
      nominalTransaction: 29000000,
      noteTransaction: "Mana ada bjir kulkas 5 pintu ",
      typeTransaction: "transactionExpense",
    },
    { id: 'TX-EX-03',
      categoryTransaction: "kebutuhan",
      colorTransaction: 'yellow',
      dateTransaction: "2015-11-16",
      nameTransaction: "Mie ayam ceu dede",
      nominalTransaction: 25000,
      noteTransaction: "enak beut dah",
      typeTransaction: "transactionExpense",
    },
    { id: 'TX-EX-04',
      categoryTransaction: "sedekah",
      colorTransaction: 'cyan',
      dateTransaction: "2020-01-16",
      nameTransaction: "Sedekah subuh",
      nominalTransaction: 2500000,
      noteTransaction: "mudah-mudahan Indonesia bebas corona",
      typeTransaction: "transactionExpense",
    },
    { id: 'TX-IN-05',
      categoryTransaction: "bonus",
      colorTransaction: 'green',
      dateTransaction: "2020-01-16",
      nameTransaction: "Bonus kantor cair",
      nominalTransaction: 2500000,
      noteTransaction: "Alhamdulillah cair jugaaaa",
      typeTransaction: "transactionIncome",
    },
    { id: 'TX-IN-06',
      categoryTransaction: "bonus",
      colorTransaction: 'green',
      dateTransaction: "2020-01-16",
      nameTransaction: "Bibi ngasih uang banyak",
      nominalTransaction: 2500000,
      noteTransaction: "Banyak beut",
      typeTransaction: "transactionIncome",
    },
  ];